/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qka0zLFOl3A
 */
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { SVGProps, useEffect, useState } from "react";
import { JSX } from "react/jsx-runtime";
import { useNavigate, useParams } from "react-router-dom";
import listingsData from "../../../_data/listings.json";

interface Listing {
  id: string;
  type: "rent" | "sale";
  title: string;
  subtitle: string;
  description: string;
  features: string[];
  featureDescriptions: string[];
  bedrooms: string;
  bathrooms: string;
  area: string;
  location: string;
  price: string;
  image_source: string[];
}

export function ListingDetails() {
  const [loading, setLoading] = useState(true);
  const [listing, setListing] = useState<Listing | null>(null);
  const navigate = useNavigate();
  const params = useParams();

  useEffect(() => {
    const item = listingsData.listings.find((item) => item.id === params.id);
    setListing(item as Listing);
    setLoading(false);
  }, [params.id, navigate]);

  if (loading)
    return (
      <div className="min-h-screen flex justify-center items-center">
        <h1 className="text-white">Loading...</h1>
      </div>
    );

  return (
    <>
      <div className="bg-gray-50 py-32 lg:py-24">
        <div className="md:max-w-screen-xl mx-auto px-4 md:px-6 flex justify-center">
          <div className="grid gap-6 lg:grid-cols-3 lg:gap-12 items-center">
            <div className="grid gap-4 col-span-1">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  {listing?.title}
                </h1>
                <div className="flex items-center gap-2">
                  <LocateIcon className="w-4 h-4 flex-shrink-0" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">
                    {listing?.location}
                  </span>
                </div>
                <h2 className="text-2xl font-bold">{listing?.price}</h2>
              </div>
              <div className="grid gap-2">
                <p className="text-sm text-gray-500 md:text-base/relaxed lg:text-sm/relaxed xl:text-base/relaxed dark:text-gray-400">
                  {listing?.description}
                </p>
              </div>
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="flex items-center gap-2">
                  <BedIcon className="w-4 h-4 flex-shrink-0" />
                  <span className="font-medium">{listing?.bedrooms} Beds</span>
                </div>
                <div className="flex items-center gap-2">
                  <BathIcon className="w-4 h-4 flex-shrink-0" />
                  <span className="font-medium">
                    {listing?.bathrooms} Baths
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <AreaChartIcon className="w-4 h-4 flex-shrink-0" />
                  <span className="font-medium">{listing?.area}</span>
                </div>
              </div>
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="grid gap-1">
                  <h3 className="text-lg font-semibold">
                    {listing?.features[0]}
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {listing?.featureDescriptions[0]}
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-semibold">
                    {listing?.features[1]}
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {listing?.featureDescriptions[1]}
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-semibold">
                    {listing?.features[2]}
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {listing?.featureDescriptions[2]}
                  </p>
                </div>
                <div className="grid gap-1">
                  <h3 className="text-lg font-semibold">
                    {listing?.features[3]}
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {listing?.featureDescriptions[3]}
                  </p>
                </div>
              </div>
              <div className="grid gap-4 sm:grid-cols-2">
                <Button size="lg" variant="outline">
                  Schedule a Tour
                </Button>
                <Button size="lg" variant="outline">
                  Make an Offer
                </Button>
              </div>
            </div>
            <div className="grid gap-4 col-span-2 lg:justify-center px-6">
              <Carousel className="w-full p-1">
                <CarouselContent>
                  {Array.from({ length: 4 }).map((_, index) => (
                    <CarouselItem key={index}>
                      <img
                        alt="listing img"
                        className="aspect-video w-full overflow-hidden rounded-xl object-cover object-center border border-gray-100 shrink-0 mx-auto"
                        height="500"
                        // src="/placeholder.svg"
                        src={listing?.image_source[index]}
                      />
                    </CarouselItem>
                  ))}
                </CarouselContent>
                <CarouselPrevious />
                <CarouselNext />
              </Carousel>
            </div>
          </div>
        </div>
      </div>
      <section className="md:max-w-screen-xl mx-auto px-4 md:px-6 py-12 lg:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-3 lg:gap-12 items-center">
            <div className="grid gap-4 col-span-1">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold text-white tracking-tighter sm:text-5xl">
                  Description
                </h2>
                <p className="text-gray-300 dark:text-gray-400">
                  {listing?.description}
                </p>
              </div>
            </div>
            <div className="grid gap-4 col-span-2 lg:justify-center">
              <div className="grid gap-4">
                <img
                  alt="House"
                  className="aspect-video overflow-hidden rounded-xl object-cover object-center shrink-0"
                  height="500"
                  src={listing?.image_source[1]}
                  width="700"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="bg-gray-50 py-24">
        <section className="md:max-w-screen-xl mx-auto px-4 md:px-6 py-12 lg:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-3 lg:gap-12 items-center">
              <div className="grid gap-4 col-span-1">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                    Features
                  </h2>
                  <ul className="grid gap-2 py-4">
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      {listing?.features[0]}
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      {listing?.features[1]}
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      {listing?.features[2]}
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      {listing?.features[3]}
                    </li>
                  </ul>
                </div>
              </div>
              <div className="grid gap-4 col-span-2 lg:justify-center">
                <img
                  alt="House"
                  className="aspect-video overflow-hidden rounded-xl object-cover object-center border border-gray-100 shrink-0"
                  height="500"
                  src={listing?.image_source[2]}
                  width="700"
                />
              </div>
            </div>
          </div>
        </section>
      </div>
      <section className="md:max-w-screen-xl mx-auto px-4 md:px-6 py-12 lg:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-3 lg:gap-12 items-center">
            <div className="grid gap-4 col-span-1">
              <div className="space-y-2">
                <h2 className="text-3xl text-white font-bold tracking-tighter sm:text-5xl">
                  Contact Agent
                </h2>
                <p className="text-gray-200">
                  Ready to make an offer or want to schedule a tour? Contact our
                  agent for more information.
                </p>
              </div>
              <form className="grid gap-4 md:grid-cols-1">
                <div className="grid gap-2">
                  <Label className="text-sm text-gray-200" htmlFor="name">
                    Name
                  </Label>
                  <Input id="name" placeholder="Enter your name" />
                </div>
                <div className="grid gap-2">
                  <Label className="text-sm text-gray-200" htmlFor="email">
                    Email
                  </Label>
                  <Input
                    id="email"
                    placeholder="Enter your email"
                    type="email"
                  />
                </div>
                <div className="grid gap-2">
                  <Label className="text-sm text-gray-200" htmlFor="message">
                    Message
                  </Label>
                  <Textarea
                    className="min-h-[100px] resize-y"
                    id="message"
                    placeholder="Enter your message"
                  />
                </div>
                <div className="grid gap-2">
                  <Button size="lg">Send</Button>
                </div>
              </form>
            </div>
            <div className="grid gap-4 col-span-2 lg:justify-center my-auto">
              <div className="grid gap-4">
                <img
                  alt="Agent"
                  className="aspect-video overflow-hidden rounded-xl object-cover object-center border border-gray-100 shrink-0"
                  height="500"
                  src="/placeholder.svg"
                  width="700"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

function LocateIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  );
}

function BedIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 4v16" />
      <path d="M2 8h18a2 2 0 0 1 2 2v10" />
      <path d="M2 17h20" />
      <path d="M6 8v9" />
    </svg>
  );
}

function BathIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 6 6.5 3.5a1.5 1.5 0 0 0-1-.5C4.683 3 4 3.683 4 4.5V17a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5" />
      <line x1="10" x2="8" y1="5" y2="7" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="7" x2="7" y1="19" y2="21" />
      <line x1="17" x2="17" y1="19" y2="21" />
    </svg>
  );
}

function AreaChartIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 3v18h18" />
      <path d="M7 12v5h12V8l-5 5-4-4Z" />
    </svg>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
